/**
 * !!! ВНИМАНИЕ! НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ !!!
 * Этот файл сгенерирован автоматически скриптом build.sh.
 * — Если вы разработчик: вносите изменения в исходники /modules/core/.
 * — Если вы поддерживаете код внутри рабочего места CraftTalk:
 *   скопируйте нужную функцию и внесите правки в клиентском js-агенте,
 *   не являющемся модулем, а затем перезапишите изменения.
 *
 * !!! WARNING! DO NOT EDIT THIS FILE !!!
 * This file is auto-generated by build.sh.
 * — If you are a developer: make changes in the source files under /modules/core/.
 * — If you maintain code inside a CraftTalk workspace:
 *   copy the function you need and apply your changes in the client-side
 *   JS agent (non-module), then overwrite accordingly.
 */

// @module core/globals
// Кросс-модульные переменные, утилиты, конфиг общего назначения

let currentDate = new Date().toLocaleDateString('ru-RU')

let ITEM_TYPES = {
    function: "function",
    commit: "commit",
}

let ROLE = {
    "USER": "user",
    "BOT": "assistant",
    "FUNCTION": "function"
}

// --- Config from agentSettings ---

let BASE_URL = agentSettings.api?.base_url
let CUSTOMER_ID = agentSettings.customer_id

const _AGENT_PARAMETERS = agentSettings.agent_parameters ?? {}
let {
    DEBUG = false,
    SHOW_THINKING = false,
} = _AGENT_PARAMETERS

let ARTICLES = agentSettings.articles ?? {}

const _STANDARD_MESSAGES = agentSettings.standard_messages ?? {}
let {
    DEFAULT_ERROR_MSG = "Что-то пошло не так, попробуйте еще раз.",
    TIMEOUT_ERROR_MSG = "Извините за задержку! Похоже, запрос занял больше времени, чем ожидалось. Пожалуйста, попробуйте снова позже.",
    NO_CONTEXT_TEXT = "К сожалению я не знаю ответ на ваш вопрос. Попробуйте задать вопрос иначе.",
} = _STANDARD_MESSAGES

// --- Validators ---

function validateHttpUrl(url) {
  if (typeof url !== 'string') {
    throw new TypeError('URL должен быть строкой')
  }
  if (!/^https?:\/\//i.test(url)) {
    throw new Error('URL должен начинаться с http:// или https://')
  }
  return true
}


// --- Utilities ---

let TRANS_MAP = {
'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo',
'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm',
'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u',
'ф': 'f', 'х': 'kh', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch',
'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya'
}
let CYRILLIC_REGEX = new RegExp(`[${Object.keys(TRANS_MAP).join('')}]`, 'g')

function translit(text) {
    return text
        .toLowerCase()
        .replace(CYRILLIC_REGEX, match => TRANS_MAP[match] || '')
        .replace(/\s+/g, '_')  // заменяем пробелы на _
        .replace(/[^a-z0-9_]/g, ''); // удаляем всё, кроме латиницы, цифр и _
}

// @module core/http
// HTTP-клиент для LLM API
// Читает конфиг URL и таймаут из agentSettings

let PROXY = agentSettings.proxy ?? {USE_PROXY: false}
let REJECT_UNAUTHORIZED = agentSettings.api?.reject_unauthorized ?? true
if (!REJECT_UNAUTHORIZED) logger.warn('TLS certificate verification is disabled (reject_unauthorized=false)')
let AGENT = new https.Agent({ rejectUnauthorized: REJECT_UNAUTHORIZED })

let URL_LLM = new URL('/context_query', agentSettings.api?.url_llm).href
let URL_LLM_SMALLTALK = new URL('/query', agentSettings.api?.url_llm).href
let URL_LLM_REPHRASE = new URL('/rephrase', agentSettings.api?.url_llm).href
let URL_LLM_COMMIT_TOOL_RESPONSES = new URL('/tool_responses', agentSettings.api?.url_llm).href
let LLM_AUTH_TOKEN = agentSettings.api?.llm_auth_token
let LLM_SETTINGS_HTTP = agentSettings.llm_settings ?? {}
let LLM_TIMEOUT = LLM_SETTINGS_HTTP.timeout ?? 60


function _debugAxiosError(error, replies) {
    if (error.response) {
        replies.debugReply(JSON.stringify(error.response.data, null, 2))
        replies.debugReply(error.response.status)
        replies.debugReply(error.response.headers)
    } else if (error.request) {
        replies.debugReply(error.request)
    } else {
        replies.debugReply('Error', error.message)
    }
}


async function _callLLM(url, data, replies, extraErrorHandling = null) {
    try {
        logger.debug(`Call LLM`)
        const config = {
            timeout: LLM_TIMEOUT * 1000,
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${LLM_AUTH_TOKEN}`,
                'Connection': 'keep-alive',
            },
            httpsAgent: AGENT
        }

        if (PROXY.USE_PROXY) {
            config.proxy = {
                protocol: 'http',
                host: PROXY.url,
                port: PROXY.port
            }
        }

        const response = await axios.post(url, data, config)
        logger.debug(`Response from LLM: ${JSON.stringify(response.data)}`)
        return response.data
    } catch (e) {
        const errorMsg = `Error requesting LLM (POST ${url}): ${e}.`
        logger.error(errorMsg)
        replies.debugReply(errorMsg)
        _debugAxiosError(e, replies)
        if (extraErrorHandling) {
            extraErrorHandling(e)
        }
        throw e
    }
}
// @module core/dialog
// @requires modules/core/globals.js
// @requires modules/core/http.js
// Парсинг истории диалога и получение истории из bot mediator

let URL_MEDIATOR_SERVICE = agentSettings.api?.url_mediator_service ?? 'http://localhost:8080'


function escapeHTML(text) {
    return text.replace(/[<>&"']/g, (match) => `&#${match.charCodeAt(0)};`)
}

function unescapeHTML(text) {
    return text.replace(/&#(\d+);/g, (_, code) => String.fromCharCode(code))
}


/**
 * Форматирование и деформатирование ответов для mediator.
 * formatResponse: ответ craftgpt → сообщения для пользователя (с reasoning в meta/isThinking).
 * unformatResponse: история из mediator → очищенные сообщения (убрать prefix, unescape HTML).
 */
class ResponseFormatter {
    /**
     * @param {string} thinkingPrefix - префикс для thinking-сообщений (напр. "*Мои размышления:* \n\n")
     */
    constructor(thinkingPrefix) {
        this.thinkingPrefix = thinkingPrefix || ''
    }

    /**
     * Преобразует нормализованный ответ в массив сообщений для отправки пользователю.
     * Ожидает, что reasoning уже извлечён в отдельное поле (через messageProcessor.fromModelFormat).
     * Добавляет артефакты для mediator: prefix и escapeHTML к reasoning.
     * @param {object} response - {answer, reasoning?, tool_calls?, log_id?}
     * @returns {Array<{text: string, meta: object, isMarkdown: boolean}>}
     */
    formatResponse(response) {
        const messages = []
        if (response.reasoning) {
            const text = this.thinkingPrefix + escapeHTML(response.reasoning)
            messages.push({ text, meta: { isThinking: "true" }, isMarkdown: false })
        }
        if (response.answer) {
            messages.push({ text: response.answer, meta: {}, isMarkdown: true })
        }
        return messages
    }

    /**
     * Очищает артефакты formatResponse из истории mediator.
     * isThinking сообщения: убирает prefix, unescape HTML.
     * Не объединяет, не удаляет — только очистка.
     * @param {Array} history - массив из getDialog()
     * @returns {Array} очищенная копия
     */
    unformatResponse(history) {
        return history.map(item => {
            if (item.isThinking) {
                let content = item.content
                if (this.thinkingPrefix && content.startsWith(this.thinkingPrefix)) {
                    content = content.slice(this.thinkingPrefix.length)
                }
                content = unescapeHTML(content)
                return { ...item, content }
            }
            return item
        })
    }
}

let responseFormatter = new ResponseFormatter(
    (_STANDARD_MESSAGES.THINKING_PREFIX) ?? ''
)


/**
 * Возвращает результат тулзы для отправки на LLM.
 * Для сценариев формирует JSON с scenario_dialogue и scenario_result.
 * @param {object} tool - элемент очереди
 * @returns {string}
 */
function getToolResult(tool) {
    const result = tool.result ?? TOOL_DONE_MESSAGE
    if (tool._scenarioDialogue) {
        return JSON.stringify({
            scenario_dialogue: tool._scenarioDialogue,
            scenario_result: result,
        })
    }
    return result
}


/**
 * Собирает нормализованную историю с явным полем reasoning.
 * Группирует сообщения по commitId (из meta) и тулзы по commit items.
 * Объединяет thinking + answer + tool_calls в одно сообщение.
 * @param {Array} history - очищенная история (после unformatResponse и processScenarios)
 * @param {Array} toolQueue - очередь из RedisQueue (тулзы + коммиты)
 * @returns {Array} [{role, message, reasoning?, tool_calls?, tool_call_id?}]
 */
function prepareHistoryWithReasoning(history, toolQueue) {
    if (!history) return []
    const filtered = history.filter(mes => mes.type !== 30)

    // Группируем тулзы по commit-ам
    const commitGroups = []
    if (toolQueue && toolQueue.length > 0) {
        let currentTools = []
        for (const item of toolQueue) {
            if (item.type === ITEM_TYPES.function && item.executed) {
                currentTools.push(item)
            } else if (item.type === ITEM_TYPES.commit) {
                commitGroups.push({
                    tools: currentTools,
                    commitId: item.commitId,
                    replyGptToMessageId: item.replyGptToMessageId,
                    reasoning: currentTools.find(t => t.reasoning)?.reasoning ?? null,
                    executed: !!item.executed,
                })
                currentTools = []
            }
        }
        // Тулзы без коммита (commit ещё не executed)
        if (currentTools.length > 0) {
            logger.warn(
                `No commit after tools in tools history: ${JSON.stringify(toolQueue)}`
            )
        }
    }

    // Индекс commitId → commit group
    const commitById = new Map()
    for (const group of commitGroups) {
        commitById.set(group.commitId, group)
    }

    // Собираем сообщения, привязанные к commitId
    const messagesByCommit = new Map()
    const commitIdSet = new Set()
    for (const mes of filtered) {
        const cid = mes.meta?.commitId
        if (cid) {
            if (!messagesByCommit.has(cid)) messagesByCommit.set(cid, [])
            messagesByCommit.get(cid).push(mes)
            commitIdSet.add(cid)
        }
    }

    // Хелпер: построить элемент результата для commit group
    function buildCommitItem(group) {
        const commitMsgs = messagesByCommit.get(group.commitId) || []
        const thinkingMsg = commitMsgs.find(m => m.isThinking)
        const answerMsg = commitMsgs.find(m => !m.isThinking)

        const reasoning = thinkingMsg?.content
            ?? answerMsg?.meta?.reasoning
            ?? group.reasoning

        const item = {
            role: 'assistant',
            message: answerMsg ? (answerMsg.content ?? answerMsg.message) : '',
            ...(reasoning && { reasoning }),
            ...(group.tools.length > 0 && {
                tool_calls: group.tools.map(t => ({
                    id: t.toolCallId,
                    type: 'function',
                    function: { name: t.name, arguments: JSON.stringify(t.args) }
                }))
            }),
        }

        const items = [item]
        // Для non-executed коммитов function results не включаем —
        // они придут отдельно как tool_responses
        if (group.executed) {
            for (const t of group.tools) {
                items.push({
                    role: ROLE.FUNCTION,
                    message: getToolResult(t),
                    tool_call_id: t.toolCallId,
                })
            }
        }
        return items
    }

    // Два итератора: по history и по commitGroups
    const result = []
    const insertedCommits = new Set()
    let gi = 0  // индекс в commitGroups

    // Хелпер: вставить следующие commit groups привязанные к данному якорю
    function insertGroupsForAnchor(anchorId) {
        while (gi < commitGroups.length) {
            const group = commitGroups[gi]
            if (group.replyGptToMessageId !== anchorId) break

            if (insertedCommits.has(group.commitId) || group.tools.length === 0) {
                gi++
                continue
            }

            result.push(...buildCommitItem(group))
            insertedCommits.add(group.commitId)
            gi++
        }
    }

    for (let i = 0; i < filtered.length; i++) {
        const mes = filtered[i]
        const cid = mes.meta?.commitId

        // Пропускаем сообщения привязанные к commitId — уже вставлены через insertGroupsForAnchor
        if (cid && insertedCommits.has(cid)) continue

        // Обычное thinking без commitId (без тулзов)
        if (mes.isThinking && !cid) {
            const next = filtered[i + 1]
            if (next && next.role === 'assistant' && !next.isThinking && !next.meta?.commitId) {
                result.push({
                    role: 'assistant',
                    message: next.content ?? next.message,
                    reasoning: mes.content,
                })
                i++
            } else {
                result.push({
                    role: 'assistant',
                    message: '',
                    reasoning: mes.content,
                })
            }
            continue
        }

        // Обычное сообщение (не привязанное к commitId)
        if (!cid) {
            const item = {
                role: mes.role,
                message: mes.content ?? mes.message,
                ...(mes.meta?.reasoning && { reasoning: mes.meta.reasoning }),
                ...(mes.tool_calls && { tool_calls: mes.tool_calls }),
                ...(mes.tool_call_id && { tool_call_id: mes.tool_call_id }),
            }
            result.push(item)

            // После user message — вставить commit groups
            if (mes.role === 'user') {
                insertGroupsForAnchor(mes.id)
            }
            continue
        }

        // Сообщение с commitId, но commit group ещё не вставлена — вставляем
        if (cid && !insertedCommits.has(cid)) {
            const group = commitById.get(cid)
            if (group) {
                result.push(...buildCommitItem(group))
            } else {
                // commitId есть в истории, но тулзы пропали — объединяем без tool_calls
                const commitMsgs = messagesByCommit.get(cid) || []
                const thinkingMsg = commitMsgs.find(m => m.isThinking)
                const answerMsg = commitMsgs.find(m => !m.isThinking)
                const reasoning = thinkingMsg?.content ?? answerMsg?.meta?.reasoning
                const item = {
                    role: 'assistant',
                    message: answerMsg ? (answerMsg.content ?? answerMsg.message) : '',
                    ...(reasoning && { reasoning }),
                }
                result.push(item)
            }
            insertedCommits.add(cid)
        }
    }

    // Оставшиеся commit groups — только если якорь существует в history
    for (; gi < commitGroups.length; gi++) {
        const group = commitGroups[gi]
        if (insertedCommits.has(group.commitId)) continue
        if (group.tools.length === 0) continue
        if (group.replyGptToMessageId && !filtered.some(m => m.id === group.replyGptToMessageId)) continue
        result.push(...buildCommitItem(group))
    }

    return result
}


function createMessageItem(id, type, message, role, meta) {
    const itemMeta = {
        ...(meta?.reasoning && { reasoning: meta.reasoning }),
        ...(meta?.commitId && { commitId: meta.commitId }),
        ...(meta?.debug && { debug: true }),
        ...(meta?.references && { references: true }),
    }
    return {
        id,
        type,
        content: message,
        role,
        ...(meta?.isThinking && { isThinking: true }),
        ...(Object.keys(itemMeta).length > 0 && { meta: itemMeta }),
    }
}


async function getBotMediatorDialogHistoryResponse(dialogId) {
    try {
        const config = {
            headers: {
                'Content-Type': 'application/json'
            },
            httpsAgent: AGENT
        }
        const requestUrl = new URL('/webhooks/mediator/messages', URL_MEDIATOR_SERVICE)
        requestUrl.searchParams.set('dialog_id', dialogId)
        const response = await axios.get(requestUrl.href, config)
        return response.data
    } catch (error) {
        logger.error("Ошибка при вызове API opbot-botmediator: " + error.message)
    }
}


function parseMediatorDialogHistory(clientDialogHistory) {
    if (!clientDialogHistory) return []
    return clientDialogHistory.reduce((acc, message) => {
        const isUserMessage = !!message.msg
        const source = isUserMessage ? message.msg : message.reply
        const { id: msgId, meta, message_type: type, message: { text } = {} } = source ?? {}
        if (type === 1 || type === 19 || type === 30) {
            const role = isUserMessage ? ROLE.USER : ROLE.BOT
            acc.push(createMessageItem(msgId, type, text, role, meta))
        }
        return acc
    }, [])
}


function getConversationId() {
    const slots = message?.slot_context?.filled_slots || []
    const slotConvId = slots.find(s => s.slot_id === 'conversation_id')
    if (slotConvId?.value) return slotConvId.value
    const metaConvId = message?.meta?.conversation_id
    if (metaConvId) return metaConvId
    return null
}

async function getMessagesByMetaResponse(customerId, omniUserId, conversationId) {
    try {
        const config = {
            headers: {
                'Content-Type': 'application/json'
            },
            httpsAgent: AGENT
        }
        const requestUrl = new URL('/mediator/messages_by_meta', URL_MEDIATOR_SERVICE)
        const response = await axios.post(requestUrl.href, {
            CustomerId: customerId,
            OmniUserId: omniUserId,
            MetaFilter: { conversation_id: conversationId },
            SortBy: "timestamp",
            SortOrder: "Asc",
            Limit: 10000
        }, config)
        return response.data
    } catch (error) {
        logger.error("Ошибка при вызове API opbot-botmediator: " + error.message)
    }
}

async function getDialog(dialog_id) {
    try {
        let clientDialogHistory = await getBotMediatorDialogHistoryResponse(dialog_id)
        return parseMediatorDialogHistory(clientDialogHistory)
    } catch (e) {
        logger.error(`Error getDialog: ${e.message}; ${JSON.stringify(e)}.`)
    }
}

async function getDialogsHistory(customerId, omniUserId) {
    try {
        const conversationId = getConversationId()
        if (!conversationId) return []
        const history = parseMediatorDialogHistory(
            await getMessagesByMetaResponse(customerId, omniUserId, conversationId)
        )
        return history || []
    } catch (e) {
        logger.error(`Error getDialogsHistory: ${e.message}; ${JSON.stringify(e)}.`)
        return []
    }
}


/**
 * Получить историю из ботмедиатора по conversation_id и убрать
 * с конца текущий вопрос, если он там есть.
 *
 * Ботмедиатор добавляет входящее сообщение в историю активного
 * диалога до того, как вызывает /message, поэтому возвращаемая
 * история заканчивается этим сообщением. craftgpt-у мы передаём
 * текущий вопрос отдельным параметром, и он сам добавляет его в
 * историю при логировании (craftgpt/llms/llm_agent.py — history +
 * [user_message]). Если не отрезать дубликат — модель увидит вопрос
 * два раза подряд.
 *
 * Использовать только там, где история точно пришла из ботмедиатора
 * (HISTORY_FROM_BOT_MEDIATOR=true).
 *
 * Между хвостовым вопросом и концом истории могут идти служебные
 * сообщения маршрутизации (type 30: switchredirect/redirect/ack):
 * в IDA-окружении входящий сценарий проходит через aiassist2, который
 * выбирает конкретного агента (gpt_ida_qwen), и этот маршрут остаётся
 * в истории после сообщения пользователя. Поэтому ищем последнее
 * «настоящее» (не type 30) сообщение, а не просто последний элемент.
 * Сами type 30 не трогаем — они нужны processScenarios.
 */
async function getMediatorHistoryForQuery(dialog_id, question, customerId, omniUserId) {
    const history = await getDialogsHistory(customerId, omniUserId)
    if (!history || history.length === 0) return history
    let lastIdx = history.length - 1
    while (lastIdx >= 0 && history[lastIdx].type === 30) lastIdx--
    if (lastIdx < 0) return history
    const last = history[lastIdx]
    if (last.role === ROLE.USER && last.content === question) {
        return [...history.slice(0, lastIdx), ...history.slice(lastIdx + 1)]
    }
    return history
}


/**
 * Собирает историю для LLM из mediator-истории и очереди тулзов.
 * Если toolQueue пуст — возвращает историю без tool_calls.
 * Если есть выполненные тулзы — вставляет tool_calls и function results,
 * сценарные сообщения упаковываются как content функции.
 *
 * @param {Array|null} mediatorHistory - из getDialog(): [{id, type, content, role, isThinking?, meta?}], null если история не управляется агентом
 * @param {Array} toolQueue - из RedisQueue.getQueue(): [{type, name, args, toolCallId, result, executed}] + commit items
 * @returns {Array|null} история в формате craftgpt, null если входная история null
 */
function buildLLMHistory(mediatorHistory, toolQueue) {
    if (mediatorHistory === null) return null
    if (mediatorHistory.length === 0) return []

    // 1. Очистка артефактов formatResponse — только наши сообщения
    //    (processScenarios должна быть вызвана до buildLLMHistory,
    //    чтобы сценарные сообщения от других агентов не прошли через unformatResponse)
    let history = responseFormatter.unformatResponse(mediatorHistory)

    // 2. Фильтруем служебные сообщения, не относящиеся к диалогу с LLM:
    //    debug (debugReply) и references (блок «Ссылки для информации»
    //    при SHOW_REFERENCES=true — нужен пользователю, но не в истории).
    history = history.filter(mes => !mes.meta?.debug && !mes.meta?.references)

    // 3. Собираем нормализованную историю с reasoning и tool_calls
    const tools = toolQueue || []
    const normHistory = prepareHistoryWithReasoning(history, tools)

    // 4. Преобразуем в формат конкретной модели
    return typeof messageProcessor !== 'undefined'
        ? messageProcessor.toModelFormat(normHistory)
        : normHistory
}


// --- Утилиты для работы со сценарной историей ---

/**
 * Возвращает подмассив arr начиная с первого элемента >= index, с index в начале.
 * Используется для нахождения позиций switchredirect-ов после заданного сообщения.
 * @param {number[]} arr - отсортированный массив индексов (напр. позиции type=30 в истории)
 * @param {number} index - начальная позиция
 * @returns {number[]}
 */
function getArrayFromInsertPosition(arr, index) {
    const insertIndex = arr.findIndex(el => el > index)
    if (insertIndex === -1) {
        return [index]
    }
    return [index, ...arr.slice(insertIndex)]
}


/**
 * Извлекает сообщения сценария между двумя switchredirect-ами в истории.
 * Возвращает [{ scenario_dialogue: [{actor, utterance}] }, [ids]] — диалог сценария и id сообщений для исключения.
 * @param {number[]} indices - индексы switchredirect-ов (из getArrayFromInsertPosition)
 * @param {Array} history - история диалога из getDialog()
 * @param {number} inputIndex - номер группы сценарных сообщений (смещение в indices)
 * @returns {[object, string[]] | []}
 */
function getScenarioMessages(indices, history, inputIndex) {
    const currentIndex = indices[inputIndex]

    if (currentIndex === undefined) {
        return []
    }

    const nextIndex = indices[inputIndex + 1]

    let messages
    if (nextIndex === undefined) {
        messages = history.slice(currentIndex + 1)
    } else {
        messages = history.slice(currentIndex + 1, nextIndex)
    }
    const reduced = messages
        .reduce((acc, mes) => {
            if (mes.type !== 30) {
                acc.messages.push({
                    actor: mes.role,
                    utterance: mes.content
                })
                acc.ids.push(mes.id)
            }
            return acc
        }, { messages: [], ids: [] })
    return [{ scenario_dialogue: reduced.messages }, reduced.ids]
}
// @module core/references
// @requires modules/core/globals.js
// @requires modules/core/markdown.js
// Форматирование ссылок на статьи и подсветки источников

let SHARE_ID = (agentSettings.agent_parameters ?? {}).SHARE_ID ?? null
const MAX_SOURCE_HIGHLIGHT_RANGES = 20
const SOURCE_HIGHLIGHT_CONTRACT_VERSION = '1'
const SOURCE_HIGHLIGHT_VERSION_PARAM = 'ctv'
const SOURCE_HIGHLIGHT_RANGE_PARAM = 'ctr'


function wrapInMarkdownCodeBlock(str) {
    // Экранируем только неэкранированные тройные кавычки
    const escapedStr = str.replace(/(?<!\\)```/g, '\\```')
    return `\`\`\`
${escapedStr}
\`\`\``
}


function isValidSourceHighlightRange(start, end) {
    return Number.isSafeInteger(start) &&
        Number.isSafeInteger(end) &&
        start >= 0 &&
        end > start
}


function rangesOverlapOrTouch(left, right) {
    return left.start <= right.end + 1 && right.start <= left.end + 1
}


function normalizeSourceHighlightRanges(ranges) {
    const seenRanges = new Set()
    const sourceRanges = Array.isArray(ranges) ? ranges : []
    const uniqueRanges = []

    sourceRanges.forEach((range, order) => {
        if (!range || !isValidSourceHighlightRange(range.start, range.end)) {
            return
        }

        const key = `${range.start}:${range.end}`

        if (!seenRanges.has(key)) {
            seenRanges.add(key)
            uniqueRanges.push({ ...range, order })
        }
    })

    const mergedRanges = uniqueRanges
        .sort((left, right) => left.start - right.start || left.end - right.end)
        .reduce((result, range) => {
            const lastRange = result[result.length - 1]

            if (!lastRange || !rangesOverlapOrTouch(lastRange, range)) {
                result.push(range)
                return result
            }

            result[result.length - 1] = {
                start: lastRange.start,
                end: Math.max(lastRange.end, range.end),
                order: Math.min(lastRange.order, range.order),
            }

            return result
        }, [])

    return mergedRanges
        .sort((left, right) => left.order - right.order)
        .map(({ start, end }) => ({ start, end }))
}


function capNormalizedSourceHighlightRanges(ranges) {
    return ranges.slice(0, MAX_SOURCE_HIGHLIGHT_RANGES)
}


function getSourceHighlightRangeMaps(fullContext) {
    const rangesByArticle = new Map()
    const symbolCodes = Array.isArray(fullContext?.symbol_code) ? fullContext.symbol_code : []
    const startIndexes = Array.isArray(fullContext?.start_index) ? fullContext.start_index : []
    const endIndexes = Array.isArray(fullContext?.end_index) ? fullContext.end_index : []

    symbolCodes.forEach((articleCode, idx) => {
        if (typeof articleCode !== 'string' || !articleCode) {
            return
        }

        const start = startIndexes[idx]
        const end = endIndexes[idx]

        if (!isValidSourceHighlightRange(start, end)) {
            return
        }

        const ranges = rangesByArticle.get(articleCode) || []
        ranges.push({ start, end })
        rangesByArticle.set(articleCode, ranges)
    })

    const validationRangesByArticle = new Map()

    rangesByArticle.forEach((ranges, articleCode) => {
        const normalizedRanges = normalizeSourceHighlightRanges(ranges)

        if (normalizedRanges.length) {
            validationRangesByArticle.set(articleCode, normalizedRanges)
        }
    })

    const fallbackRangesByArticle = new Map()

    validationRangesByArticle.forEach((ranges, articleCode) => {
        fallbackRangesByArticle.set(
            articleCode,
            capNormalizedSourceHighlightRanges(ranges),
        )
    })

    return {
        validationRangesByArticle,
        fallbackRangesByArticle,
    }
}


function getSourceHighlightRangesByArticle(fullContext) {
    return getSourceHighlightRangeMaps(fullContext).fallbackRangesByArticle
}


function addSourceHighlightSearchParams(url, ranges) {
    url.searchParams.delete(SOURCE_HIGHLIGHT_VERSION_PARAM)
    url.searchParams.delete(SOURCE_HIGHLIGHT_RANGE_PARAM)

    if (ranges.length === 0) {
        return
    }

    url.searchParams.set(SOURCE_HIGHLIGHT_VERSION_PARAM, SOURCE_HIGHLIGHT_CONTRACT_VERSION)
    ranges.forEach(({ start, end }) => {
        url.searchParams.append(SOURCE_HIGHLIGHT_RANGE_PARAM, `${start}:${end}`)
    })
}


function getArticleUrl(intentId, ranges = []) {
    const baseArticleUrl = SHARE_ID
        ? `${BASE_URL}/app/share/${SHARE_ID}/article/${intentId}`
        : `${BASE_URL}/app/project/${CUSTOMER_ID}/knowledge-base/article/view/${intentId}`
    const normalizedRanges = capNormalizedSourceHighlightRanges(
        normalizeSourceHighlightRanges(ranges),
    )

    if (normalizedRanges.length === 0) {
        return baseArticleUrl
    }

    const url = new URL(baseArticleUrl)
    addSourceHighlightSearchParams(url, normalizedRanges)

    return url.toString()
}


function getTitleWithUrl(intentId, title, ranges = []) {
    return `[${title}](${getArticleUrl(intentId, ranges)})`
}


function getContextSourceHighlightRange(fullContext, idx) {
    const start = fullContext?.start_index?.[idx]
    const end = fullContext?.end_index?.[idx]

    return isValidSourceHighlightRange(start, end)
        ? [{ start, end }]
        : []
}


function addUrlToContextTitle(fullContext, sourceHighlightsEnabled = false) {
    fullContext.symbol_code.forEach((intentId, idx) => {
        const title = fullContext.context[idx].title
        const ranges = sourceHighlightsEnabled
            ? getContextSourceHighlightRange(fullContext, idx)
            : []

        fullContext.context[idx].title = getTitleWithUrl(intentId, title, ranges)
    })
}


function getArticlePathPrefixes() {
    const prefixes = [
        `/app/project/${CUSTOMER_ID}/knowledge-base/article/view/`,
    ]

    if (SHARE_ID) {
        prefixes.push(`/app/share/${SHARE_ID}/article/`)
    }

    return prefixes
}


function getKnowledgeBaseArticleCodeFromUrl(destination) {
    let url
    let baseUrl

    try {
        url = new URL(destination, BASE_URL)
        baseUrl = new URL(BASE_URL)
    } catch (_) {
        return null
    }

    if (url.origin !== baseUrl.origin) {
        return null
    }

    const articlePathPrefix = getArticlePathPrefixes()
        .find(prefix => url.pathname.startsWith(prefix))

    if (!articlePathPrefix) {
        return null
    }

    const encodedArticleCode = url.pathname.slice(articlePathPrefix.length)

    try {
        const articleCode = decodeURIComponent(encodedArticleCode)

        if (
            !articleCode ||
            articleCode.includes('/') ||
            articleCode.includes('\\')
        ) {
            return null
        }

        return articleCode
    } catch (_) {
        return null
    }
}


function parseSourceHighlightRanges(url) {
    const versions = url.searchParams.getAll(SOURCE_HIGHLIGHT_VERSION_PARAM)
    const rawRanges = url.searchParams.getAll(SOURCE_HIGHLIGHT_RANGE_PARAM)

    if (
        versions.length !== 1 ||
        versions[0] !== SOURCE_HIGHLIGHT_CONTRACT_VERSION ||
        rawRanges.length === 0
    ) {
        return null
    }

    const parsedRanges = []

    for (const rawRange of rawRanges) {
        const match = /^(\d+):(\d+)$/.exec(rawRange)

        if (!match) {
            return null
        }

        const start = Number(match[1])
        const end = Number(match[2])

        if (!isValidSourceHighlightRange(start, end)) {
            return null
        }

        parsedRanges.push({ start, end })
    }

    return parsedRanges
}


function isSourceHighlightSelectionValid(url, availableRanges) {
    const selectedRanges = parseSourceHighlightRanges(url)

    if (!selectedRanges || !Array.isArray(availableRanges)) {
        return false
    }

    return selectedRanges.every(selectedRange =>
        availableRanges.some(availableRange =>
            availableRange.start <= selectedRange.start &&
            selectedRange.end <= availableRange.end
        )
    )
}


function getEnrichedArticleUrl(
    destination,
    validationRangesByArticle,
    fallbackRangesByArticle = validationRangesByArticle,
) {
    const articleCode = getKnowledgeBaseArticleCodeFromUrl(destination)

    if (!articleCode || !validationRangesByArticle.has(articleCode)) {
        return destination
    }

    try {
        const url = new URL(destination, BASE_URL)
        const availableRanges = validationRangesByArticle.get(articleCode)

        if (isSourceHighlightSelectionValid(url, availableRanges)) {
            return destination
        }

        const fallbackRanges = fallbackRangesByArticle.has(articleCode)
            ? fallbackRangesByArticle.get(articleCode)
            : availableRanges
        const normalizedFallbackRanges = capNormalizedSourceHighlightRanges(
            normalizeSourceHighlightRanges(fallbackRanges),
        )

        addSourceHighlightSearchParams(url, normalizedFallbackRanges)

        return url.toString()
    } catch (_) {
        return destination
    }
}


function enrichMarkdownArticleLinks(
    markdown,
    validationRangesByArticle,
    fallbackRangesByArticle = validationRangesByArticle,
) {
    if (
        typeof markdown !== 'string' ||
        !validationRangesByArticle ||
        typeof validationRangesByArticle.has !== 'function' ||
        typeof validationRangesByArticle.get !== 'function' ||
        validationRangesByArticle.size === 0
    ) {
        return markdown
    }

    let result = ''
    let cursor = 0

    while (cursor < markdown.length) {
        const linkStart = markdown.indexOf('[', cursor)

        if (linkStart === -1) {
            result += markdown.slice(cursor)
            break
        }

        if (linkStart > 0 && markdown[linkStart - 1] === '!') {
            result += markdown.slice(cursor, linkStart + 1)
            cursor = linkStart + 1
            continue
        }

        const titleEnd = markdown.indexOf(']', linkStart + 1)

        if (titleEnd === -1 || markdown[titleEnd + 1] !== '(') {
            result += markdown.slice(cursor, linkStart + 1)
            cursor = linkStart + 1
            continue
        }

        const urlStart = titleEnd + 2
        const urlEnd = markdown.indexOf(')', urlStart)

        if (urlEnd === -1) {
            result += markdown.slice(cursor, linkStart + 1)
            cursor = linkStart + 1
            continue
        }

        const destination = markdown.slice(urlStart, urlEnd)
        const enrichedDestination = getEnrichedArticleUrl(
            destination,
            validationRangesByArticle,
            fallbackRangesByArticle,
        )

        result += markdown.slice(cursor, urlStart)
        result += enrichedDestination
        cursor = urlEnd
    }

    return result
}


function enrichResponseArticleLinks(
    response,
    validationRangesByArticle,
    fallbackRangesByArticle = validationRangesByArticle,
) {
    if (!response || typeof response.answer !== 'string') {
        return response
    }

    const answer = enrichMarkdownArticleLinks(
        response.answer,
        validationRangesByArticle,
        fallbackRangesByArticle,
    )

    if (answer === response.answer) {
        return response
    }

    return { ...response, answer }
}


function getReferencesFromScenarios(context) {
    if (!context || context.length === 0) return ''
    const uniqueTitles = [...new Set(context.map(c => c.title).filter(Boolean))]
    if (uniqueTitles.length === 0) return ''
    return "### Ссылки для информации:" + uniqueTitles.map(t => `\n\n*  ${t}`).join('')
}


function getReferences(full_context, rangesByArticle = new Map()) {
    let references = ""
    const articles_counts = new Map()
    const articles_titles = new Map()

    // Считаем упоминания каждой статьи
    full_context.symbol_code.forEach((intent_id, idx) => {
        const prev_count = articles_counts.get(intent_id) || 0
        articles_counts.set(intent_id, prev_count + 1)
        articles_titles.set(intent_id, full_context.title[idx])
    })

    // Сортируем по убыванию числа упоминаний
    const sorted_counts = Array.from(articles_counts.entries())
        .sort((a, b) => b[1] - a[1])

    sorted_counts.forEach(([intent_id]) => {
        const url = getArticleUrl(intent_id, rangesByArticle.get(intent_id))
        references += `\n\n*  [${articles_titles.get(intent_id)}](${url})`
    })

    if (references !== "")
        references = "### Ссылки для информации:" + references
    return references
}
// @module core/context
// @requires modules/core/http.js
// Поиск контекста в базе знаний и обработка сценариев

let URL_CONTEXT_SEARCH = new URL('/search', agentSettings.api?.url_context_search).href
let URL_CONTEXT_SEARCH_SCENARIOS = new URL('/search_in_scenarios', agentSettings.api?.url_context_search).href

const _CONTEXT_SETTINGS = agentSettings.context_settings ?? {}
let {
    LAST_CONTEXT_PRICE = 0.19,
    OTHER_CONTEXT_PRICE = 3.1,
    ADD_OTHER_CONTEXT = true,
    MAX_CONTEXTS = 10,
    MAX_COMPLEX_SCENARIOS = 5,
    MAX_COMPLEX_QUESTION_EXAMPLES_LENGTH = 1000,
    CONTEXT_FROM_SCENARIOS = false,
    ADD_COMPLEX_SCENARIOS_TO_TOOLS = false,
    FILTERS = [],
    SIMPLE_INCLUDE_QUESTIONS = false,
    SIMPLE_MAX_QUESTIONS = 5,
    SIMPLE_INCLUDE_CONDITIONS = false,
    SIMPLE_TITLE_WITH_URL = true,
    RECORD_TYPE = null,
    CATALOG_IDS = null,
    TAGS = null,
} = _CONTEXT_SETTINGS


async function getContext(question, replies) {
    replies.debugReply(JSON.stringify(question))
    logger.debug(`Call CONTEXT SEARCH service`)
    let response
    try {
        response = await axios.post(
            URL_CONTEXT_SEARCH,
            {
                text: question,
                customer_id: CUSTOMER_ID,
                record_type: RECORD_TYPE,
                catalog_symbol_code: CATALOG_IDS,
                tags: TAGS,
                output_format: "json-vikhr",
                filters: FILTERS,
                size: MAX_CONTEXTS > 0 ? MAX_CONTEXTS : 100,
            }
        )

        logger.info("Response from CONTEXT SEARCH:" + JSON.stringify(response.data))
    } catch(e) {
        logger.error(`Error requesting context search: ${e}.`)
        replies.debugReply(`Error requesting context search: ${e}.`)
        _debugAxiosError(e, replies)
        throw e
    }
    const fullContext = response.data
    if (MAX_CONTEXTS > -1) {
        Object.keys(fullContext).forEach(key => {
            fullContext[key] = fullContext[key].slice(0, MAX_CONTEXTS)
        })
    }
    return fullContext
}


async function getContextFromScenarios(question, replies) {
    replies.debugReply(JSON.stringify(question))
    logger.debug(`Call CONTEXT SEARCH service (scenarios)`)
    let response
    try {
        response = await axios.post(
            URL_CONTEXT_SEARCH_SCENARIOS,
            {
                text: question,
                customer_id: CUSTOMER_ID,
                record_type: RECORD_TYPE,
                catalog_symbol_code: CATALOG_IDS,
                tags: TAGS,
                filters: FILTERS,
                size: Math.max(
                    MAX_CONTEXTS > 0 ? MAX_CONTEXTS : 100,
                    MAX_COMPLEX_SCENARIOS > 0 ? MAX_COMPLEX_SCENARIOS : 100,
                ),
            }
        )

        logger.info("Response from CONTEXT SEARCH (scenarios):" + JSON.stringify(response.data))
    } catch(e) {
        logger.error(`Error requesting context search (scen.): ${e}.`)
        replies.debugReply(`Error requesting context search (scen.): ${e}.`)
        _debugAxiosError(e, replies)
        throw e
    }
    const fullContext = response.data
    if (MAX_CONTEXTS > -1) {
        fullContext.simple = fullContext.simple.slice(0, MAX_CONTEXTS)
    }
    if (MAX_COMPLEX_SCENARIOS > -1) {
        fullContext.complex = fullContext.complex.slice(0, MAX_COMPLEX_SCENARIOS)
    }
    return fullContext
}


// --- Scenario conversion helpers ---

function isExceededLimitQuestions(ctxPartsLength, question) {
    const possibleLength = ctxPartsLength + question.length
    const maxLength = MAX_COMPLEX_QUESTION_EXAMPLES_LENGTH
    const isExceeded = possibleLength > maxLength
    if (isExceeded)
        logger.warn(`Length context exceeded(max:${MAX_COMPLEX_QUESTION_EXAMPLES_LENGTH}, possible:${possibleLength}). Question example is deleted: '${question}'`)
    return isExceeded
}


// Исключает цепочки с недопустимыми типами блоков
function isAvailableChain(excludedTypes, chain) {
    const types = chain.blocks?.map(b => b.type) || []
    return !types.some(type => excludedTypes.includes(type))
}


/**
 * Преобразует условия в читаемую строку с кастомизируемыми операторами
 */
function formatConditionsToString(posConditions, negConditions, options = {}) {
    const {
        ifPrefix = 'ЕСЛИ',
        andNotPrefix = 'И НЕ',
        notPrefix = 'НЕ',
        andOperator = 'И',
        orOperator = 'ИЛИ'
    } = options

    const formatCondition = (cond) => {
        return `${cond.slot} ${cond.condition} "${cond.value}"`
    }

    const formatAndGroup = (andGroup) => {
        if (!andGroup || andGroup.length === 0) return ''
        return andGroup.map(formatCondition).join(` ${andOperator} `)
    }

    const buildOrString = (conditions) => {
        if (!conditions || conditions.length === 0) return { str: '', compound: false }
        const groups = conditions.map(formatAndGroup).filter(Boolean)
        if (groups.length === 0) return { str: '', compound: false }
        if (groups.length === 1) return { str: groups[0], compound: false }
        return {
            str: groups.map(g => `(${g})`).join(` ${orOperator} `),
            compound: true,
        }
    }

    const pos = buildOrString(posConditions)
    const neg = buildOrString(negConditions)

    if (!pos.str && !neg.str) return ''

    const wrap = (s) => `(${s})`

    if (pos.str && neg.str) {
        const p = pos.compound ? wrap(pos.str) : pos.str
        const n = neg.compound ? wrap(neg.str) : neg.str
        return `${ifPrefix} ${p} ${andNotPrefix} ${n}`
    }
    if (pos.str) {
        return `${ifPrefix} ${pos.str}`
    }
    const n = neg.compound ? wrap(neg.str) : neg.str
    return `${ifPrefix} ${notPrefix} ${n}`
}


/** Преобразует ответ из контекстсерча в формате цепочки сценария в текст для LLM.
 * Структура цепочки: @see Chain typedef в исходных скриптах.
 */
function formatChainSimple(chain) {
    let ctxParts = []
    const blocks = chain.blocks || []

    for (const block of blocks) {
        if (!block?.type) continue

        if (block.type === "message") {
            ctxParts.push(block.text || "")
        } else if (block.type === "button") {
            ctxParts.push(`\n### ${block.text || ""}`)
        } else if (block.type === "start") {
            ctxParts.push(`\n## ${block.text || ""}`)
        } else if (block.type === "questions" && SIMPLE_INCLUDE_QUESTIONS) {
            if (Array.isArray(block.text) && block.text.length > 0) {
                const questions = block.text.slice(0, SIMPLE_MAX_QUESTIONS)
                ctxParts.push(`Примеры вопросов: ${questions.join(", ")}`)
            }
        } else if (block.type === "condition" && SIMPLE_INCLUDE_CONDITIONS) {
            const condStr = formatConditionsToString(
                block.pos_conditions, block.neg_conditions
            )
            if (condStr) {
                ctxParts.push(`**Условие:** ${condStr}`)
            }
        }
    }

    return ctxParts.join("\n")
}


function formatChainComplex(chain) {
    let ctxParts = []
    let ctxPartsLength = 0
    const blocks = chain.blocks || []
    if (!isAvailableChain(["button", "condition"], chain))
        return ""
    for (const block of blocks) {
        if (!block?.type) continue
        if (block.type === "questions") {
            block.text.forEach(question => {
                if (question && !isExceededLimitQuestions(ctxPartsLength, question)) {
                    ctxPartsLength += question.length
                    ctxParts.push(question)
                }
            })
        }
    }
    return ctxParts.join(",")
}


function extractTitleFromChain(chain, availableTypes, withUrl) {
    for (const block of (chain.blocks ?? [])) {
        if (availableTypes.includes(block.type)) {
            if (withUrl)
                return getTitleWithUrl(block.symbol_code, block.text)
            else
                return block.text
        }
    }
    return ""
}


function extractSymbolCodeFromChain(chain, availableTypes) {
    for (const block of (chain.blocks ?? [])) {
        if (availableTypes.includes(block.type)) {
            return block.symbol_code
        }
    }
    return ""
}


function convertScenariosSimple(chains) {
    let contexts = []
    let docId = 0
    for (const chain of chains) {
        if (!chain?.blocks?.length) continue
        const content = formatChainSimple(chain)
        if (!content) continue
        contexts.push({
            id: docId++,
            title: extractTitleFromChain(chain, ["start"], SIMPLE_TITLE_WITH_URL),
            content: content
        })
    }
    return contexts
}


function convertScenariosComplex(chains) {
    let contexts = []
    let docId = 0
    for (const chain of chains) {
        if (!chain?.blocks?.length) continue
        const content = formatChainComplex(chain)
        if (!content) continue
        const symbol_code = extractSymbolCodeFromChain(chain, ["complex_scenario"])
        if (!symbol_code) continue
        const title = extractTitleFromChain(chain, ["complex_scenario"], false)
        if (!title) continue
        contexts.push({
            id: docId++,
            title: title,
            content: content,
            symbol_code: symbol_code,
        })
    }
    return contexts
}


function convertScenariosToContext(chains) {
    return convertScenariosSimple(chains)
}


function convertScenariosToTools(chains) {
    return convertScenariosComplex(chains)
}
// @module core/slots
// Управление слотами: конфиг, чтение, инъекция в промпты, хранение для ответа

class SlotManager {
    /**
     * @param {object} settings - agentSettings из платформы
     * @param {object} message - объект входящего сообщения с slot_context
     */
    constructor(settings, message) {
        const cfg = settings.slots ?? {}
        this.agentSlots = cfg.agent_slots ?? {SCENARIO_RESULT: "scenario_result"}
        this.useSlots = cfg.use_slots ?? false
        this.placeholder = cfg.user_slots_placeholder ?? "## Слоты:"
        this.userSlots = cfg.user_slots ?? []
        this.replySlots = {}
        this._message = message
    }

    /**
     * Возвращает значение слота из входящего сообщения по его id.
     * @param {string} slotId
     * @returns {string|undefined}
     */
    getSlotValue(slotId) {
        return this._message.slot_context.filled_slots
            .find(slot => slot.slot_id === slotId)?.value
    }

    /**
     * Преобразует массив определений слотов в структурированный список
     * с текущими значениями из входящего сообщения.
     * Если значение содержит ";", берётся последний элемент.
     * @param {Array<{id: string, description: string}>} slots
     * @returns {Array<{slotId: string, slotDescription: string, slotValue: string|null}>}
     */
    getSlots(slots) {
        if (!slots || !Array.isArray(slots)) return []
        const filledSlots = this._message.slot_context.filled_slots
        return slots.map(slot => {
            const filledSlot = filledSlots.find(f => f.slot_id === slot.id)
            let slotValue = null
            if (filledSlot?.value) {
                const values = filledSlot.value.split(';')
                slotValue = values.length > 0 ? values[values.length - 1] : null
            }
            return { slotId: slot.id, slotDescription: slot.description, slotValue }
        })
    }

    /**
     * Устанавливает значение слота в исходящем ответе.
     * Для удаления слота передайте value = null.
     * @param {string} slotId
     * @param {string|null} value
     */
    setSlot(slotId, value) {
        this.replySlots[slotId] = value
    }

    /**
     * Объединяет переданные слоты с уже накопленными в replySlots.
     * @param {object|undefined} slots - объект {slotId: value}
     */
    mergeSlots(slots) {
        if (slots) Object.assign(this.replySlots, slots)
    }

    /**
     * Подставляет текущие значения пользовательских слотов в шаблон промпта.
     * Если useSlots=false, возвращает шаблон без изменений.
     * @param {string} template - шаблон промпта с placeholder (напр. "## Слоты:")
     * @returns {string}
     */
    injectSlotsIntoPrompt(template) {
        if (!this.useSlots) return template
        const userSlots = this.getSlots(this.userSlots)
        const slotsBlock = userSlots.length > 0
            ? userSlots.map(s =>
                `- ${s.slotId}. - ${s.slotDescription}: **${s.slotValue ?? 'не заполнено'}**`
              ).join('\n')
            : '- Нет заполненных слотов'
        return template.replace(
            this.placeholder,
            `${this.placeholder}\n${slotsBlock}`
        )
    }
}

let slotManager = new SlotManager(agentSettings, message)

// Обратная совместимость — глобальные алиасы
let AGENT_SLOTS = slotManager.agentSlots
let USE_SLOTS = slotManager.useSlots

// Обратная совместимость — свободные функции-обёртки
function getSlotValue(slotId) {
    return slotManager.getSlotValue(slotId)
}

function getSlots(slots) {
    return slotManager.getSlots(slots)
}
// @module core/rag
// @requires modules/core/http.js
// @requires modules/core/slots.js
// LLM-запросы: smalltalk, rag, rephrase, commitToolResponses

const _LLM_SETTINGS_RAG = agentSettings.llm_settings ?? {}
let LLM_TEMPERATURE = _LLM_SETTINGS_RAG.temperature ?? 0.6
let LLM_TEMPERATURE_SMALLTALK = _LLM_SETTINGS_RAG.temperature_smalltalk ?? 0.7
let LLM_TOP_P = _LLM_SETTINGS_RAG.top_p ?? 0.95
let LLM_TOP_K = _LLM_SETTINGS_RAG.top_k ?? 20
let LLM_MIN_P = _LLM_SETTINGS_RAG.min_p ?? 0.0
// null → craftgpt применит свой дефолт (config.max_tokens)
let LLM_MAX_TOKENS = _LLM_SETTINGS_RAG.max_tokens ?? null

const _AP_RAG = agentSettings.agent_parameters ?? {}
let {
    DO_REPHRASE = false,
    REPHRASE_N_GENERATIONS = 4,
    REPHRASE_SAMPLES_PER_GENERATION = 4,
    ENABLE_THINKING_SMALLTALK = true,
    ENABLE_THINKING_RAG = true,
    SMALLTALK_IF_NO_CONTEXT = true,
} = _AP_RAG


function applyPromptOverrides() {
    const prompts = agentSettings.prompts
    if (!prompts) return
    if (prompts.system_template) LLM_SYSTEM_TEMPLATE = prompts.system_template
    if (prompts.system_template_smalltalk) LLM_SYSTEM_TEMPLATE_SMALLTALK = prompts.system_template_smalltalk
    if (prompts.rag_template) RAG_TEMPLATE = prompts.rag_template
    if (prompts.smalltalk_template) SMALLTALK_TEMPLATE = prompts.smalltalk_template
    if (prompts.rag_document_template) RAG_DOCUMENT_TEMPLATE = prompts.rag_document_template
    if (prompts.rephrase_prompt_1) REPHRASE_PROMPT_1 = prompts.rephrase_prompt_1
    if (prompts.rephrase_prompt_2) REPHRASE_PROMPT_2 = prompts.rephrase_prompt_2
}


async function smalltalk(question, dialogId, history, replies) {
    const requestData = {
        question: SMALLTALK_TEMPLATE.replace('{question}', question),
        dialog_id: dialogId,
        history: history,
        temperature: LLM_TEMPERATURE_SMALLTALK,
        top_p: LLM_TOP_P,
        top_k: LLM_TOP_K,
        min_p: LLM_MIN_P,
        max_tokens: LLM_MAX_TOKENS,
        instruction: slotManager.injectSlotsIntoPrompt(LLM_SYSTEM_TEMPLATE_SMALLTALK),
        tools: TOOLS,
        last_context_price: LAST_CONTEXT_PRICE,
        other_context_price: OTHER_CONTEXT_PRICE,
        add_other_context: ADD_OTHER_CONTEXT
    }

    return await _callLLM(
        URL_LLM_SMALLTALK,
        requestData,
        replies
    )
}


async function rag(question, context, dialogId, history, replies) {
    const requestData = {
        question: question,
        dialog_id: dialogId,
        history: history,
        context: context,
        temperature: LLM_TEMPERATURE,
        top_p: LLM_TOP_P,
        top_k: LLM_TOP_K,
        min_p: LLM_MIN_P,
        max_tokens: LLM_MAX_TOKENS,
        system_template: slotManager.injectSlotsIntoPrompt(LLM_SYSTEM_TEMPLATE),
        user_template: RAG_TEMPLATE,
        document_template: RAG_DOCUMENT_TEMPLATE,
        join_sep: RAG_JOIN_SEP,
        tools: TOOLS,
        last_context_price: LAST_CONTEXT_PRICE,
        other_context_price: OTHER_CONTEXT_PRICE,
        add_other_context: ADD_OTHER_CONTEXT
    }

    return await _callLLM(
        URL_LLM,
        requestData,
        replies,
        (e) => {
            replies.debugReply(
                "<h3>Контекст</h3>" + JSON.stringify(context, null, 2)
            )
        }
    )
}


async function commitToolResponses(
    tool_responses, dialogId, history, replies, tool_choice
) {
    const requestData = {
        tool_responses: tool_responses,
        dialog_id: dialogId,
        history: history,
        temperature: LLM_TEMPERATURE,
        top_p: LLM_TOP_P,
        top_k: LLM_TOP_K,
        min_p: LLM_MIN_P,
        max_tokens: LLM_MAX_TOKENS,
        tools: TOOLS,
        tool_choice: tool_choice,
        last_context_price: LAST_CONTEXT_PRICE,
        other_context_price: OTHER_CONTEXT_PRICE,
        add_other_context: ADD_OTHER_CONTEXT
    }

    logger.debug(`User question ${message.message.text}. Commit tool responses: ${JSON.stringify(tool_responses)}`)
    return await _callLLM(
        URL_LLM_COMMIT_TOOL_RESPONSES,
        requestData,
        replies
    )
}


async function rephrase(question, prompt, dialogId, history, replies) {
    const requestData = {
        question: question,
        prompt: prompt,
        dialog_id: dialogId,
        history: history,
        n_generations: REPHRASE_N_GENERATIONS,
        samples_per_generation: REPHRASE_SAMPLES_PER_GENERATION,
        last_context_price: LAST_CONTEXT_PRICE,
        other_context_price: OTHER_CONTEXT_PRICE,
        add_other_context: ADD_OTHER_CONTEXT
    }

    const response = await _callLLM(
        URL_LLM_REPHRASE,
        requestData,
        replies
    )
    return response.texts
}
// @module core/mcp
// @requires modules/core/globals.js   (translit)
// Превращает MCP-серверы из agentSettings.mcp_servers в стандартные тулзы.
// TOOLS и availableFunctions объявляются клиентским скриптом ниже по цепочке
// конкатенации; здесь только мутируем их.

// Конфиг MCP-серверов: [{ alias, transport: "http"|"sse", url, headers?,
// enabled?, tool_filter? }]
let MCP_SERVERS = agentSettings.mcp_servers ?? []

// Имя тулзы: <alias>__<tool>. Префикс alias — конвенция, не гарантия;
// уникальность проверяется в registerMcpTools().
const _mcpToolName = (alias, name) => `${translit(String(alias))}__${translit(String(name))}`

// MCP inputSchema — это JSON Schema, кладём её напрямую в parameters.
const _mcpToOpenAITool = (toolName, mcpTool) => ({
    type: "function",
    function: {
        name: toolName,
        description: mcpTool.description ?? "",
        parameters: mcpTool.inputSchema ?? { type: "object", properties: {} },
    },
})

// Сплющивает сырой результат MCP { content: [...], isError } в строку для LLM.
const _mcpResultToString = (res) => {
    const content = res?.content
    let text
    if (Array.isArray(content)) {
        text = content
            .map(p => (p && p.type === "text" && typeof p.text === "string") ? p.text : JSON.stringify(p))
            .join("\n")
    } else if (typeof content === "string") {
        text = content
    } else {
        text = JSON.stringify(res ?? "")
    }
    return res?.isError ? `ERROR: ${text}` : text
}

// Обычная (несценарная) async-тулза: вызывает MCP-инструмент и возвращает строку.
// Маршрутизация (на какой сервер/инструмент) зашита в замыкании.
const _makeMcpToolFn = (server, originalName) => async (args) => {
    try {
        const res = await mcp.callTool(server, originalName, args)
        return _mcpResultToString(res)
    } catch (e) {
        logger.error(`MCP tool ${originalName} failed: ${e}`)
        return `ERROR: не удалось выполнить инструмент ${originalName}: ${e}`
    }
}

// Регистрирует тулзы всех включённых MCP-серверов в TOOLS и availableFunctions.
// Недоступный сервер пропускается; конфликт имён — бросает ошибку.
async function registerMcpTools() {
    if (typeof mcp === "undefined" || !mcp) {
        logger.warn("MCP helper `mcp` недоступен в песочнице — пропускаю MCP-тулзы")
        return
    }
    // Занятые имена — ключи availableFunctions, чтобы не перетереть штатную тулзу.
    const usedNames = new Set(
        availableFunctions && typeof availableFunctions === "object"
            ? Object.keys(availableFunctions)
            : []
    )
    for (const server of MCP_SERVERS) {
        if (!server || server.enabled === false) continue
        const alias = server.alias || "mcp"
        if (!server.alias) logger.warn(`MCP-сервер без alias — использую "mcp": ${server.url}`)
        if (!server.url) {
            logger.warn(`MCP server "${alias}" без url — пропускаю`)
            continue
        }
        // Сетевые ошибки listTools — пропускаем сервер.
        let tools
        try {
            tools = await mcp.listTools(server)
        } catch (e) {
            logger.error(`Не удалось получить инструменты MCP server "${alias}" (${server.url}): ${e}`)
            continue
        }
        const filter = Array.isArray(server.tool_filter) && server.tool_filter.length
            ? new Set(server.tool_filter)
            : null
        const registered = []
        for (const t of tools) {
            if (!t || !t.name) continue
            if (filter && !filter.has(t.name)) continue
            const toolName = _mcpToolName(alias, t.name)
            if (usedNames.has(toolName)) {
                throw new Error(
                    `MCP: конфликт имён тулз — "${toolName}" (сервер "${alias}", инструмент "${t.name}") ` +
                    `уже занят. Проверьте уникальность alias серверов и имён инструментов ` +
                    `(в т.ч. после translit: дефисы/точки вырезаются, пробелы → "_").`
                )
            }
            usedNames.add(toolName)
            TOOLS.push(_mcpToOpenAITool(toolName, t))
            availableFunctions[toolName] = _makeMcpToolFn(server, t.name)
            registered.push(toolName)
        }
        logger.info(`MCP "${alias}" (${server.url}): зарегистрировано тулз ${registered.length} [${registered.join(", ")}]`)
    }
}
// @module core/tools_loop
// @requires modules/core/http.js
// @requires modules/core/dialog.js
// @requires modules/core/slots.js
// Цикл выполнения tool calls: ScenarioNotReadyError, SwitchRedirectPropagate,
// RedisQueue, runToolsLoop

let AGENT_NAME = agentSettings.agent_name
let ROUTE_TO_SELF_AGENT = `/switchredirect ${AGENT_NAME}`


class SwitchRedirectPropagate extends Error {
    constructor(switchredirect) {
        super("switchredirect call")
        this.name = "SwitchRedirectPropagate"
        this.switchredirect = switchredirect
    }
}

const _AP_TOOLS = agentSettings.agent_parameters ?? {}
let {
    MAX_CYCLES = 5,
    TOOL_DONE_MESSAGE = "Done",
} = _AP_TOOLS

const _SM_TOOLS = agentSettings.standard_messages ?? {}
// action и текст кнопки должны совпадать с обработкой в runToolsLoop (action:"cancel" / "прервать")
let {
    MESSAGE_CANCEL_WAITING = "Готов ответить на ваш следующий вопрос! Чем ещё могу помочь?",
    MESSAGE_WHILE_WAITING_ERROR = `Чтобы обеспечить качественную обработку ваших запросов, мы сначала должны завершить работу по предыдущему вопросу. Пожалуйста, дождитесь ответа, после чего сможете задать новый вопрос.
\`\`\`buttons(placement:keyboard)
::
[Прервать](type:action action:cancel color:negative)
\`\`\`
`,
} = _SM_TOOLS


function scenario(scenarioName) {
    return function(originalFunction) {
        const wrapped = async function(...args) {
            // Вызываем оригинальную функцию
            return await originalFunction.apply(this, args)
        }

        // Помечаем как сценарную
        wrapped.isScenario = true
        wrapped.returnsResult = true
        // Ожидаем, что результат сценария будет записан в слот с именем scenarioName
        if (scenarioName === undefined) {
            wrapped.scenarioName = AGENT_SLOTS.SCENARIO_RESULT
        } else if (scenarioName === null) {
            wrapped.scenarioName = null
            wrapped.returnsResult = false
        } else {
            wrapped.scenarioName = scenarioName
        }

        return wrapped
    }
}

function switchredirect(intent_id) {
    return `/switchredirect aiassist2 intent_id="${intent_id}"`
}


let KEYS = {
    QUEUE_KEY: "function_queue",
    N_CYCLES_KEY: "n_cycles",
}

let WAIT_FOR_SCENARIO_TTL = 60 * 60 * 24  // 24 часа


/**
 * Обрабатывает сценарные тулзы: извлекает сценарные сообщения из истории,
 * сохраняет scenario_dialogue в поле _scenarioDialogue тулзы.
 * Удаляет switchredirect-ы и сценарные сообщения из истории.
 * Не мутирует входные массивы.
 *
 * @param {Array} history - история из getDialog()
 * @param {Array} tools - очередь из RedisQueue
 * @param {string} routeToSelfAgent - строка switchredirect обратно на наш агент
 * @returns {{ history: Array, tools: Array }}
 */
function processScenarios(history, tools, routeToSelfAgent) {
    const newHistory = [...history]
    const newTools = tools.map(t => ({ ...t }))
    const indicesToRemove = new Set()
    let currentAnchorIndex = -1  // трекаем текущий user message

    for (let i = 0; i < newTools.length; i++) {
        const tool = newTools[i]
        if (tool.type !== 'function' || !tool.started || tool.scenario === null) continue

        const commit = newTools.slice(i + 1).find(t => t.type === ITEM_TYPES.commit)
        if (!commit?.replyGptToMessageId) continue

        let anchorIndex = newHistory.findIndex(m => m.id === commit.replyGptToMessageId)
        if (anchorIndex !== -1) {
            currentAnchorIndex = anchorIndex
        } else {
            anchorIndex = currentAnchorIndex
        }
        if (anchorIndex === -1) continue

        // Найти диапазон сценария: от первого switchredirect (не наш) после якоря
        // до switchredirect обратно (наш), включая оба
        let scenarioStart = -1
        let scenarioEnd = -1
        for (let j = anchorIndex + 1; j < newHistory.length; j++) {
            if (indicesToRemove.has(j)) continue
            if (newHistory[j].type === 30) {
                if (scenarioStart === -1 && newHistory[j].content !== routeToSelfAgent) {
                    scenarioStart = j
                } else if (scenarioStart !== -1 && newHistory[j].content === routeToSelfAgent) {
                    scenarioEnd = j
                    break
                }
            }
        }

        if (scenarioStart === -1) continue

        // Извлечь сценарные сообщения (type !== 30, между switchredirect-ами)
        const scenarioDialogue = []
        const endIdx = scenarioEnd !== -1 ? scenarioEnd : newHistory.length
        for (let j = scenarioStart; j <= endIdx && j < newHistory.length; j++) {
            indicesToRemove.add(j)
            if (newHistory[j].type !== 30) {
                scenarioDialogue.push({
                    actor: newHistory[j].role,
                    utterance: newHistory[j].content,
                })
            }
        }

        newTools[i] = { ...tool, _scenarioDialogue: scenarioDialogue }

        // Нормализация replyGptToMessageId в commit — только если id не найден в history
        const commitMsgExists = newHistory.some(m => m.id === commit.replyGptToMessageId)
        if (!commitMsgExists) {
            const lastUserMsg = newHistory.filter((m, idx) => m.role === 'user' && !indicesToRemove.has(idx)).pop()
            if (lastUserMsg) {
                const commitIdx = newTools.indexOf(commit)
                newTools[commitIdx] = { ...newTools[commitIdx], replyGptToMessageId: lastUserMsg.id }
            }
        }
    }

    return {
        history: newHistory.filter((_, idx) => !indicesToRemove.has(idx)),
        tools: newTools,
    }
}


class ScenarioNotReadyError extends Error {
    constructor(scenarioName) {
        super(`Unexpected run of the tools agent during waiting for ${scenarioName}`)
        this.name = "ScenarioNotReadyError"
    }
}


let RedisQueue = class {
    constructor(redisClient, deleteSlotFn, debugLogFn) {
        this.redis = redisClient
        this.deleteSlot = deleteSlotFn
        this.debugReply = debugLogFn
    }

    // Хук: вызывается после завершения сценарной тулзы, до markAsExecuted.
    // Для fire-and-forget сценариев scenarioResult === undefined.
    // Дефолт — no-op. Клиенты переопределяют для side-эффектов (например, markdownReply).
    async onScenarioCompleted(item, scenarioResult, replies) {}

    // Добавление задачи в очередь
    async addFunction(queue, name, args, toolCallId, reasoning) {
        const newItem = {
            type: ITEM_TYPES.function,
            name: name,
            args: args,
            toolCallId: toolCallId,
            executed: false,
            started: false,
            scenario: null,
            result: null,
            reasoning: reasoning ?? null,
        }
        queue.push(newItem)
    }

    // Добавление коммита
    async addCommit(queue, commitId, replyGptToMessageId) {
        queue.push({
            type: ITEM_TYPES.commit,
            commitId: commitId,
            replyGptToMessageId: replyGptToMessageId,
            executed: false,
        })
    }

    // Получение и обработка очереди
    async processQueue(queue, commitFcResults, replies) {  // -> {answer, tool_calls, log_id} | undefined
        let lastCommitIndex = -1

        for (let i = 0; i < queue.length; i++) {
            const item = queue[i]

            // пропустим выполненные элементы
            if (item.type === ITEM_TYPES.function && item.executed) {
                continue
            }
            if (item.type === ITEM_TYPES.commit && item.executed) {
                lastCommitIndex = i
                continue
            }
            // Обработка невыполненной функции
            if (item.type === ITEM_TYPES.function) {
                if (item.started) {
                    // запущенные сценарии
                    let scenarioResult
                    if (item.scenario !== null) {
                        // scenario that returns a result
                        scenarioResult = this.getScenarioAnswer(item.scenario)
                        logger.debug(`scenarioResult ${scenarioResult}`)
                        if (scenarioResult === undefined) {
                            throw new ScenarioNotReadyError(item.scenario)
                        }
                        this.deleteSlot(item.scenario)
                    }
                    await this.onScenarioCompleted(item, scenarioResult, replies)
                    await this.markAsExecuted(queue, i, scenarioResult)
                } else {
                    // Запускаем функции
                    const func = availableFunctions[item.name]
                    this.debugReply(
                        `Calling ${item.name}(${JSON.stringify(item.args)})`
                    )
                    if (func.isScenario) {
                        await this.markAsStartedScenario(queue, i, func.scenarioName)
                        const res = await func(item.args, replies)

                        if (res?.[0] === "/") {  // /switchredirect as expected
                            throw new SwitchRedirectPropagate(res)
                        }
                        // else it is probably an error, so return it as result
                        await this.markAsExecuted(queue, i, res)
                    } else {
                        const res = await func(item.args)
                        await this.markAsExecuted(queue, i, res)
                    }
                }
                continue
            }

            // Обработка коммита
            if (item.type === ITEM_TYPES.commit && !item.executed) {
                const functionsToCommit = []
                let commitIndex = i

                // Сбор выполненных функций текущего батча
                for (let j = lastCommitIndex + 1; j < commitIndex; j++) {
                    if (queue[j].type === ITEM_TYPES.function && queue[j].executed) {
                        functionsToCommit.push(queue[j])
                    } else if (!queue[j].executed) {
                        logger.warn(`Unexpected item before commit: ${JSON.stringify(queue[j])}`)
                        this.debugReply(`Unexpected item before commit: ${JSON.stringify(queue[j])}`)
                    }
                }
                this.debugReply(`Comitting ${JSON.stringify(functionsToCommit, null, 2)}`)
                const nCycles = await this.incNCycles()
                this.debugReply(`Cycle ${nCycles} / ${MAX_CYCLES}`)
                const toolСhoice = nCycles >= MAX_CYCLES ? "none" : "auto"

                const llmRes = await commitFcResults(
                    functionsToCommit,
                    toolСhoice,
                    queue
                )
                await this.markAsExecuted(queue, commitIndex)
                return llmRes
            }
        }
    }

    // Получить результат сценария из слота
    getScenarioAnswer(scenarioName) {
        if (scenarioName === null) {
            return null
        }
        return getSlotValue(scenarioName)
    }

    // Пометить функцию как запущенную
    async markAsStartedScenario(queue, i, scenarioName) {
        const item = queue[i]
        item.started = true
        item.scenario = scenarioName
        await this.saveQueue(queue)
    }

    // Пометить функцию как выполненную
    async markAsExecuted(queue, i, result) {
        const item = queue[i]
        item.executed = true
        item.result = result
        await this.saveQueue(queue)
        if (item.name) this.debugReply(`${item.name} finished with ${result}`)
    }

    async clearQueue() {
        for (const item of await this.getQueue()) {
            if (item.scenario !== null && item.scenario !== undefined) {
                this.deleteSlot(item.scenario)
            }
        }
        this.debugReply(JSON.stringify(
            await this.saveQueue([])
        ))
        this.debugReply(await this.getQueue())
        await this.resetNCycles()
    }

    async cancelUnexecuted() {
        const queue = await this.getQueue()
        for (const item of queue) {
            if (!item.executed && item.scenario !== null && item.scenario !== undefined) {
                this.deleteSlot(item.scenario)
            }
        }
        const remaining = queue.filter(item => item.executed)
        await this.saveQueue(remaining)
        await this.resetNCycles()
    }

    async getQueue() {
        const data = await this.redis.get(KEYS.QUEUE_KEY)
        this.debugReply(`Get queue: ${JSON.stringify(data)}`)
        return data ? JSON.parse(data) : []
    }

    async saveQueue(queue) {
        // Удаляем _scenarioDialogue перед записью — обогащение хранится только в памяти
        const clean = queue.map(item => {
            if (item._scenarioDialogue !== undefined) {
                const { _scenarioDialogue, ...rest } = item
                return rest
            }
            return item
        })
        return await this.redis.set(KEYS.QUEUE_KEY, JSON.stringify(clean), WAIT_FOR_SCENARIO_TTL)
    }

    async incNCycles() {
        let n_cycles = await this.redis.get(KEYS.N_CYCLES_KEY) ?? 0
        n_cycles++
        await this.redis.set(KEYS.N_CYCLES_KEY, n_cycles, WAIT_FOR_SCENARIO_TTL)
        return n_cycles
    }

    async resetNCycles() {
        await this.redis.set(KEYS.N_CYCLES_KEY, 0, WAIT_FOR_SCENARIO_TTL)
    }
}


function setScenariosForTransfer(scenarios) {
    availableFunctions["transfer_to_scenario"] = scenario(null)(function ({id}) {
        const scenarios_ = scenarios
        if (scenarios_[id] === undefined) {
            logger.error(`Scenario ${id} is not defined. Available: ${JSON.stringify(Object.keys(scenarios_))}`)
            return `ERROR: scenario ${id} is not defined`
        }
        return switchredirect(scenarios_[id])
    })
}


/**
 * Добавляет сценарии в tool transfer_to_scenario.
 * @param {Array<{title: string, content: string, symbol_code: string}>} scenarios
 */
function addCustomScenariosToTools(scenarios) {
    if (!scenarios || scenarios.length === 0) return

    TOOLS = TOOLS.map(tool => {
        if (tool.function.name !== "transfer_to_scenario") return tool
        const content = scenarios
            .map(s => `- ${translit(s.title)} Примеры вопросов: ${s.content}`)
            .join('\n')
        tool.function.parameters.properties.id.description =
            `Идентификатор сценария, на который выполняешь перевод. Доступные значения и примеры вопросов (вызывай этот сценарий, если сообщение пользователя похоже на один из примеров вопросов):\n${content}`
        tool.function.parameters.properties.id.enum = scenarios.map(s => translit(s.title))
        return tool
    })

    const scenarioMap = scenarios.reduce((dict, s) => {
        dict[translit(s.title)] = s.symbol_code
        return dict
    }, {})
    logger.info(`Formatted scenarios for tool 'transfer_to_scenario'. ${JSON.stringify(scenarioMap)}`)
    setScenariosForTransfer(scenarioMap)
}


async function enqueueToolCalls(redisClient, queue, toolCalls, commitId, replyMessageId, pendingReasoning, replies) {
    let functionAdded = false
    for (const call of toolCalls) {
        if (!call.function || !call.function.name) continue
        const funcName = call.function.name
        if (!availableFunctions[funcName]) {
            throw new Error(`Функция ${funcName} не найдена`)
        }
        const funcArgs = JSON.parse(call.function.arguments)
        replies.debugReply(`Enqueuing tool ${funcName}(${JSON.stringify(funcArgs, null, 2)})`)
        await redisClient.addFunction(queue, funcName, funcArgs, call.id, pendingReasoning)
        pendingReasoning = null  // привязываем только к первой тулзе
        functionAdded = true
    }
    if (functionAdded) {
        await redisClient.addCommit(queue, commitId, replyMessageId)
        await redisClient.saveQueue(queue)
    } else {
        await redisClient.resetNCycles()
    }
    return functionAdded
}


async function runToolsLoop(question, dialog_id, history, replies, sendMessageToLLMOpts, sendMessageToLLM, _printResponse) {
    const redisClient = new RedisQueue(
        agentStorage.dialogStorage,
        replies.deleteSlot,
        replies.debugReply
    )

    // check whether we want to erase the queue
    if (question.toLowerCase() === "прервать" || message.message.action === "cancel") {
        replies.debugReply("Cancelling all tool calls")
        await Promise.all([
            redisClient.cancelUnexecuted(),
            replies.markdownReply(MESSAGE_CANCEL_WAITING)
        ])
        return { cancelled: true }
    }

    // Обработка сценариев: извлечение scenario_dialogue из истории,
    // обогащение results тулзов. До buildLLMHistory, чтобы
    // сценарные сообщения от других агентов не прошли через unformatResponse.
    let queue = await redisClient.getQueue()
    if (history !== null) {
        const processed = processScenarios(history, queue, ROUTE_TO_SELF_AGENT)
        history = processed.history
        queue = processed.tools
    }

    const commitFcResults = async function (fcResults, toolСhoice, fullQueue) {
        logger.debug("fcResults " + JSON.stringify(fcResults))
        const functionsToCommit = fcResults.map(tool => ({
            role: ROLE.FUNCTION,
            content: getToolResult(tool),
            tool_call_id: tool.toolCallId
        }))
        // Перезапрашиваем историю из медиатора напрямую (без trim
        // через getMediatorHistoryForQuery): для /tool_responses
        // craftgpt не приклеивает question отдельно, поэтому в
        // истории должен остаться оригинальный user-msg. Заодно
        // подхватывается isThinking при SHOW_THINKING=true.
        let currentHistory = history
        if (history !== null && dialog_id) {
            const freshHistory = await getDialogsHistory(message.user.customer_id, message.user.omni_user_id)
            const processed = processScenarios(freshHistory, fullQueue, ROUTE_TO_SELF_AGENT)
            currentHistory = processed.history
        }
        const llmHistory = buildLLMHistory(currentHistory, fullQueue)
        return await commitToolResponses(
            functionsToCommit, dialog_id, llmHistory, replies, toolСhoice
        )
    }

    // pull scenario answers, call next functions
    let response
    let finalAnswer
    let responsePrinted = false
    try {
        response = await redisClient.processQueue(queue, commitFcResults, replies)
    } catch (error) {
        if (error instanceof ScenarioNotReadyError) {
            if (question) {
                await replies.markdownReply(MESSAGE_WHILE_WAITING_ERROR)
                replies.debugReply(error.message)
                return { cancelled: true }
            }
        }
        throw error
    }

    // Если не было обработки тулзов, то отправляем сообщение пользователя на ллмку
    if (response === undefined) {
        if (!question) {
            logger.warn("Empty question with empty queue, skipping")
            replies.debugReply("Empty question with empty queue, skipping")
            return { cancelled: true }
        }
        response = await sendMessageToLLM(question, dialog_id, history, replies, sendMessageToLLMOpts)
        responsePrinted = true
        finalAnswer = response.answer
    } else if (question) {
        logger.warn(`Both tools handling and user's question (${question}) have gotten. The user's question will be ignored.`)
        replies.debugReply(`Both tools handling and user's question (${question}) have gotten. The user's question will be ignored.`)
    }

    while (response !== undefined) {
        const commitId = uuid.v4()
        let pendingReasoning = null
        if (response.answer && !responsePrinted) {
            pendingReasoning = await _printResponse(response, replies, commitId)
        }
        await enqueueToolCalls(
            redisClient, queue, response.tool_calls ?? [],
            commitId, message.id,
            pendingReasoning, replies
        )
        response = await redisClient.processQueue(queue, commitFcResults, replies)
        responsePrinted = false
    }
    replies.debugReply("Finish")
    return { finalAnswer }
}
// @module core/main
// @requires modules/core/globals.js
// @requires modules/core/http.js
// @requires modules/core/dialog.js
// @requires modules/core/references.js
// @requires modules/core/context.js
// @requires modules/core/slots.js
// @requires modules/core/rag.js
// @requires modules/core/tools_loop.js
// _sendReply, _printResponse, sendMessageToLLM, main, _mainBody, setScenariosForTransfer, runEntrypoint

let IS_QUERY_REPORT = message?.meta?.isQueryReport

const _AP_MAIN = agentSettings.agent_parameters ?? {}
let {
    SHOW_REFERENCES = false,
    SHOW_CONTEXT = false,
    USE_HISTORY = true,
    HISTORY_FROM_BOT_MEDIATOR = false,
    ENABLE_SOURCE_HIGHLIGHTS = false,
} = _AP_MAIN

function _sendReply(text, slots, meta = {}) {
    const reply = agentApi.makeMarkdownReply(text)

    slotManager.mergeSlots(slots)

    logger.debug(JSON.stringify(reply.message.text))

    return agentApi.sendMessage({
        MessageMarkdown: reply.message.text,
        SendMessageParams: {
            ProjectId: reply.customer_id,
            OmniUserId: reply.omni_user_id,
            Sender: {},
            DestinationChannel: {
                ChannelId: reply.channel_id,
                ChannelUserId: message.user.channel_user_id
            },
            FilledSlots: slotManager.replySlots,
            Meta: meta
        }
    }, logger)
        .then(result => {
            if (!result.Ok) {
                const errMsg = `${JSON.stringify(result.Errors)} during sending ${JSON.stringify(reply)}`
                logger.error(errMsg)
                if (DEBUG) {
                    agentApi.sendMessage({
                        MessageMarkdown: errMsg,
                        SendMessageParams: {
                            ProjectId: reply.customer_id,
                            OmniUserId: reply.omni_user_id,
                            Sender: {},
                            FilledSlots: slotManager.replySlots
                        }
                    }, logger)
                }
            }
        })
        .catch(e => logger.error(`Error sending reply: ${e}.`))
    // don't block, return Promise
}


async function _printResponse(response, replies, commitId) {
    if (IS_QUERY_REPORT) {
        return null
    }

    const normalized = messageProcessor.fromModelFormat(response)
    const messages = responseFormatter.formatResponse(normalized)
    let pendingReasoning = null

    for (const msg of messages) {
        const meta = { ...msg.meta }
        if (commitId) {
            meta.commitId = commitId
        }

        if (msg.meta.isThinking) {
            if (SHOW_THINKING) {
                await replies.textReply(msg.text, meta)
            } else {
                pendingReasoning = msg.text
                replies.debugReply(msg.text)
            }
        } else {
            if (pendingReasoning) {
                meta.reasoning = pendingReasoning
                pendingReasoning = null
            }
            if (msg.isMarkdown) {
                await replies.markdownReply(msg.text, meta)
            } else {
                await replies.textReply(msg.text, meta)
            }
        }
    }

    // Если reasoning остался без основного сообщения (tool_calls кейс) —
    // возвращаем для записи в RedisQueue при enqueue тулзов
    return pendingReasoning
}


async function sendMessageToLLM(question, dialog_id, history, replies, opts = {}) {
    const {
        use_rag = true,
        use_think = ENABLE_THINKING_SMALLTALK,
        use_rephrase = DO_REPHRASE,
        use_smalltalk = SMALLTALK_IF_NO_CONTEXT,
        topicSlots = {}
    } = opts

    history = buildLLMHistory(history, [])

    let contextsearch_texts = question
    // Generate rephrases of user question
    if (use_rephrase) {
        // rephrases1 = await rephrase(question, REPHRASE_PROMPT_1, dialog_id, replies)
        let rephrases2 = await rephrase(question, REPHRASE_PROMPT_2, dialog_id, history, replies)
        logger.info(`rephrases2 значение: ${rephrases2}`)
        contextsearch_texts = [question]
        // contextsearch_texts = contextsearch_texts.concat(rephrases1)
        contextsearch_texts = contextsearch_texts.concat(rephrases2)
        logger.info(`contextsearch_texts значение: ${contextsearch_texts}`)
    }

    // Search for relevant context
    let context // [{doc_id: str, title: str, content: str, symbol_code?: str},...]
    let fullContext  // response from classical intent search
    let scenariosContext // response from scenario intent search
    let sourceHighlightValidationRangesByArticle = new Map()
    let sourceHighlightFallbackRangesByArticle = new Map()

    // Skip RAG if use_rag is disabled
    if (!use_rag) {
        context = []
    } else if (CONTEXT_FROM_SCENARIOS) {
        scenariosContext = await getContextFromScenarios(contextsearch_texts, replies)
        context = convertScenariosToContext(scenariosContext.simple)
        // Если нашелся сложный сценарий
        if (ADD_COMPLEX_SCENARIOS_TO_TOOLS && scenariosContext.complex) {
            addCustomScenariosToTools(convertScenariosToTools(scenariosContext.complex))
        }
    } else {
        fullContext = await getContext(contextsearch_texts, replies)

        if (ENABLE_SOURCE_HIGHLIGHTS) {
            const sourceHighlightRangeMaps = getSourceHighlightRangeMaps(fullContext)
            sourceHighlightValidationRangesByArticle =
                sourceHighlightRangeMaps.validationRangesByArticle
            sourceHighlightFallbackRangesByArticle =
                sourceHighlightRangeMaps.fallbackRangesByArticle
        }

        addUrlToContextTitle(fullContext, ENABLE_SOURCE_HIGHLIGHTS)
        context = fullContext.context
    }

    let response
    // Context not found
    if (context?.length === 0) {
        logger.info(`Context not found for question "${question}"`)
        replies.debugReply(`Context not found for question "${question}"`)

        if (use_smalltalk) {
            response = await smalltalk(question, dialog_id, history, replies)
            await _printResponse(response, replies)
            return response
        } else {
            replies.markdownReply(NO_CONTEXT_TEXT)
            return {answer: NO_CONTEXT_TEXT, tool_calls: [], log_id: null}
        }
    }

    // Answer with context (RAG)
    response = await rag(question, context, dialog_id, history, replies)
    response = enrichResponseArticleLinks(
        response,
        sourceHighlightValidationRangesByArticle,
        sourceHighlightFallbackRangesByArticle,
    )

    // References to articles
    let references = ''
    if (SHOW_REFERENCES) {
        references = CONTEXT_FROM_SCENARIOS
            ? getReferencesFromScenarios(context)
            : getReferences(fullContext, sourceHighlightFallbackRangesByArticle)
    }

    // Final answers
    await _printResponse(response, replies)

    if (SHOW_REFERENCES && references) {
        replies.markdownReply(references, { references: "true" })
    }

    if (SHOW_CONTEXT) {
        const contextToShow = CONTEXT_FROM_SCENARIOS ? scenariosContext : fullContext
        replies.textReply(
            "<h3>Контекст</h3>" + JSON.stringify(contextToShow, null, 2),
            {},
            true
        )
    }
    return response
}


async function main() {
    let replies = {}
    let response
    // Helpers to add reply
    function textReply(text, meta={},  wrapCodeBlock=false) {
        if (IS_QUERY_REPORT) {
            return
        }
        let reply
        if (wrapCodeBlock) {
            reply = wrapInMarkdownCodeBlock(String(text))
        } else {
            reply = String(text)
        }
        return _sendReply(reply, undefined, meta)
    }
    function markdownReply(text, meta={}) {
        logger.debug(`Message for user: ${text}`)
        if (!IS_QUERY_REPORT) {
            return _sendReply(String(text), undefined, meta)
        }
    }
    function debugReply(text) {
        // never await debugReply
        if (DEBUG && !IS_QUERY_REPORT) {
            return _sendReply(wrapInMarkdownCodeBlock(String(text)), undefined, { debug: "true" })
        }
    }
    function deleteSlot(slot) {
        slotManager.replySlots[slot] = null
    }
    replies.textReply = textReply
    replies.markdownReply = markdownReply
    replies.debugReply = debugReply
    replies.deleteSlot = deleteSlot

    try {
        response = await _main(replies)
    } catch (e) {
        if (e instanceof SwitchRedirectPropagate) {
            if (IS_QUERY_REPORT) {
                return e.switchredirect
            }
            await replies.markdownReply(e.switchredirect)
            return response
        }
        logger.error(`main error ${e}`)
        logger.error(JSON.stringify(e.stack))
        logger.error(JSON.stringify(e.cause))
        if (e.code === 'ECONNABORTED') {
            if (IS_QUERY_REPORT) {
                return TIMEOUT_ERROR_MSG
            }
            await replies.textReply(TIMEOUT_ERROR_MSG)
        } else {
            if (IS_QUERY_REPORT) {
                return DEFAULT_ERROR_MSG
            }
            await replies.textReply(DEFAULT_ERROR_MSG)
        }
        if (DEBUG) {
            replies.debugReply(`ERROR: ${e}`)
            replies.debugReply(e.stack)
        }
    }
    return response
}


async function _mainBody(replies, sendMessageToLLMOpts = {}) {
    // Main code
    let question = message.message.text
    logger.info(`question ${question}`)
    replies.debugReply(JSON.stringify(message.slot_context, null, 2))
    replies.debugReply(JSON.stringify(message.message, null, 2))

    // Get dialog_id
    let dialog_id = null
    let history = null
    if (USE_HISTORY) {
        if (IS_QUERY_REPORT) {
            dialog_id = message.meta?.dialog_id
            history = message.meta?.history
        } else {
            const dialog_response = await agentApi.getDialogId(
                message.user.omni_user_id,
                message.user.customer_id
            )

            dialog_id = dialog_response.Response
            history = HISTORY_FROM_BOT_MEDIATOR
                ? await getMediatorHistoryForQuery(dialog_id, question, message.user.customer_id, message.user.omni_user_id)
                : null
        }
    }

    logger.info(`ID диалога клиента: ${JSON.stringify(dialog_id)}`)
    logger.info(`История диалога клиента: ${JSON.stringify(history)}`)

    let finalAnswer

    // Регистрируем тулзы с MCP-серверов до первого обращения к LLM (TOOLS уходит
    // в LLM внутри runToolsLoop/sendMessageToLLM).
    if (typeof registerMcpTools === 'function' && MCP_SERVERS.length) {
        await registerMcpTools()
    }

    if (typeof runToolsLoop === 'function') {
        const result = await runToolsLoop(
            question,
            dialog_id,
            history,
            replies,
            sendMessageToLLMOpts,
            sendMessageToLLM,
            _printResponse
        )
        if (result.cancelled) return
        finalAnswer = result.finalAnswer
    } else {
        // Простой путь без тулзов
        const response = await sendMessageToLLM(question, dialog_id, history, replies, sendMessageToLLMOpts)
        finalAnswer = response.answer
    }

    if (IS_QUERY_REPORT) {
        const normalized = messageProcessor.fromModelFormat({ answer: finalAnswer })
        return normalized.answer
    }
}


function runEntrypoint() {
    if (message.message_type === 1 && !IS_QUERY_REPORT) {
        main()
            .then(_ => {
                resolve([])
            })
            .catch(error => {
                logger.error(`Error: ${error}`)
                resolve([agentApi.makeMarkdownReply(error)])
            })
    } else if (IS_QUERY_REPORT) {
        main()
            .then(res => {
                resolve({ answer: res })
            })
            .catch(error => {
                logger.error(`Error: ${error}`)
                resolve(error)
            })
    } else {
        logger.info(`Message type: ${message.message_type}. Skip.`)
        resolve([]) // SKIP
    }
}
