#!/bin/bash
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cat > "$SCRIPT_DIR/gpt_core.js" <<'HEADER'
/**
 * !!! ВНИМАНИЕ! НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ !!!
 * Этот файл сгенерирован автоматически скриптом build.sh.
 * — Если вы разработчик: вносите изменения в исходники /modules/core/.
 * — Если вы поддерживаете код внутри рабочего места CraftTalk:
 *   скопируйте нужную функцию и внесите правки в клиентском js-агенте,
 *   не являющемся модулем, а затем перезапишите изменения.
 *
 * !!! WARNING! DO NOT EDIT THIS FILE !!!
 * This file is auto-generated by build.sh.
 * — If you are a developer: make changes in the source files under /modules/core/.
 * — If you maintain code inside a CraftTalk workspace:
 *   copy the function you need and apply your changes in the client-side
 *   JS agent (non-module), then overwrite accordingly.
 */

HEADER
cat "$SCRIPT_DIR"/modules/core/[0-9]*.js >> "$SCRIPT_DIR/gpt_core.js"
